//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapResult.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MapResult.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;{0}&apos;,&apos;U&apos;) IS NOT NULL DROP TABLE {0}
        ///
        ///CREATE TABLE {0}(
        ///	Id int identity(1,1),
        ///		PRIMARY KEY(Id),		
        ///	[Loinc] [varchar](50) NULL,
        ///	[Result] [varchar](254) NULL,
        ///	[LoincScale] [varchar](254) NULL,
        ///	[MappedYN] [varchar](1) NULL,
        ///	[MapFunc] [varchar](50) NULL,
        ///	[Inequality] [varchar](2) NULL,
        ///	[Number] [varchar](100) NULL,
        ///	[AfterDecimal] [int] NULL,
        ///	[Field1] [varchar](100) NULL,
        ///	[Field2] [varchar](100) NULL,
        ///	[General] [varchar](30) NULL,
        ///	[Pretty] [varchar](100) NULL,
        ///) 
        ///.
        /// </summary>
        internal static string CreateOutputTable {
            get {
                return ResourceManager.GetString("CreateOutputTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF OBJECT_ID(&apos;{0}&apos;,&apos;U&apos;) IS NOT NULL DROP TABLE {0}
        ///
        ///CREATE TABLE {0}(
        ///	Id int identity(1,1),
        ///		PRIMARY KEY(Id),		
        ///	[LabId] [varchar](50) NULL,
        ///	[Result] [varchar](254) NULL,
        ///	[MappedYN] [varchar](1) NULL,
        ///	[MapFunc] [varchar](50) NULL,
        ///	[Inequality] [varchar](2) NULL,
        ///	[Number] [varchar](100) NULL,
        ///	[AfterDecimal] [int] NULL,
        ///	[Field1] [varchar](100) NULL,
        ///	[Field2] [varchar](100) NULL,
        ///	[General] [varchar](30) NULL,
        ///	[Pretty] [varchar](100) NULL,
        ///) 
        ///.
        /// </summary>
        internal static string CreateOutputTable_MapWithoutLoinc {
            get {
                return ResourceManager.GetString("CreateOutputTable_MapWithoutLoinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if object_id(&apos;{2}&apos;) is not null begin drop table {2} end;
        ///
        ///select  e.*,  m.MappedYN, m.Number, m.Inequality, m.AfterDecimal, m.Field1, m.General
        ///into {2}
        ///from [{0}] e
        ///left join [{1}] m
        ///	on m.Result = e.{3}
        ///	and m.Loinc = e.{4}
        ///.
        /// </summary>
        internal static string DoMap {
            get {
                return ResourceManager.GetString("DoMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update [Dflt].[{0}]
        ///set ScaleType = 
        ///	(
        ///		case 
        ///			when ScaleType = &apos;* &apos; then null
        ///			when ScaleType = &apos;SET&apos; then null
        ///			when ScaleType = &apos;Nominal&apos; then &apos;Nom&apos;
        ///			when ScaleType = &apos;Narrative&apos; then &apos;Nar&apos;
        ///			when ScaleType = &apos;*Unknown at this time*&apos; then null
        ///			when ScaleType = &apos;Ordinal&apos; then &apos;Ord&apos;
        ///			when ScaleType = &apos;NULL&apos; then null
        ///			when ScaleType = &apos;Document&apos; then &apos;Doc&apos;
        ///			when ScaleType = &apos;Multi&apos; then &apos;Multi&apos;
        ///			when ScaleType = &apos;Quantitative&apos; then &apos;Qn&apos;
        ///			when ScaleType = &apos;*Missing*&apos; th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MapLoincScaleType {
            get {
                return ResourceManager.GetString("MapLoincScaleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Loinc.LOINC, Loinc.ScaleType, plc.Sta3n, plc.PatientSID, plc.LabChemSpecimenDateTime, plc.RequestingStaffSID, plc.RequestingLocationSID, plc.Units, plc.Abnormal, plc.RefHigh, plc.RefLow, plc.LabChemSID, Loinc.LOINCSID, plc.LabChemResultValue, plc.LabChemResultNumericValue, plc.LabChemCompleteDateTime 
        ///into [PCS_LABMed].[Dflt].[{0}]  
        ///FROM [PCS_LABMed].[Dflt].ETL_LabList LabList 
        ///     JOIN [RDWWork].Dim.LOINC Loinc 
        ///         ON LabList.Loinc = Loinc.LOINC 
        ///     JOIN [RDWWork].Chem.PatientLabChem  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VaLabQuery {
            get {
                return ResourceManager.GetString("VaLabQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select --o.PAT_ENC_CSN_ID
        ///	  o.order_proc_id
        ///	--, o.proc_code
        ///	, o.display_name
        ///	, r.line
        ///	, r.component_id
        ///	, cc.loinc_code
        ///	, loincScale.Name LoincScale
        ///	, cc.EXTERNAL_NAME
        ///	--, opi.PARENT_ORDER_ID
        ///	, r.ord_value
        ///	--, r.ord_num_value
        ///	--, r.REFERENCE_UNIT
        ///	, r.REFERENCE_LOW
        ///	, r.REFERENCE_HIGH
        ///	--, r.result_in_range_yn --less informative for non-quanti. results
        ///	, zrf.Name result_flag_c
        ///	--, zrs.Name result_status_c	
        ///	--, zrdt.Name data_type_c
        ///	, o.ORDER_INST
        ///	--, o.INSTANTIATED_TIME
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YaleLabQuery {
            get {
                return ResourceManager.GetString("YaleLabQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select o.PAT_ENC_CSN_ID
        ///	, o.order_proc_id
        ///	, o.proc_code
        ///	, o.display_name
        ///	, r.line
        ///	, r.component_id
        ///	, cc.loinc_code
        ///	, loincScale.Name LoincScale
        ///	, cc.EXTERNAL_NAME
        ///	, opi.PARENT_ORDER_ID
        ///	, r.ord_value
        ///	, r.ord_num_value
        ///	, r.REFERENCE_UNIT
        ///	, r.REFERENCE_LOW
        ///	, r.REFERENCE_HIGH
        ///	, r.result_in_range_yn
        ///	, zrf.Name result_flag_c
        ///	, zrs.Name result_status_c	
        ///	, zrdt.Name data_type_c
        ///	, o.ORDER_INST
        ///	, o.INSTANTIATED_TIME
        ///	, o2.specimn_taken_time
        ///	, r.result_time
        ///	, llb.LLB_NAME
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YaleLabQuery_LabList {
            get {
                return ResourceManager.GetString("YaleLabQuery_LabList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select o.PAT_ENC_CSN_ID
        ///	, o.order_proc_id
        ///	, o.proc_code
        ///	, o.display_name
        ///	, r.line
        ///	, r.component_id
        ///	, cc.loinc_code
        ///	, loincScale.Name LoincScale
        ///	, cc.EXTERNAL_NAME
        ///	--, opi.PARENT_ORDER_ID
        ///	, r.ord_value
        ///	--, r.ord_num_value
        ///	, r.REFERENCE_UNIT
        ///	, r.REFERENCE_LOW
        ///	, r.REFERENCE_HIGH
        ///	--, r.result_in_range_yn --less informative for non-quanti. results
        ///	, zrf.Name result_flag_c
        ///	, zrs.Name result_status_c	
        ///	, zrdt.Name data_type_c
        ///	, o.ORDER_INST
        ///	--, o.INSTANTIATED_TIME
        ///	, o2.spec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string YaleLabQuery_NullLoinc {
            get {
                return ResourceManager.GetString("YaleLabQuery_NullLoinc", resourceCulture);
            }
        }
    }
}
