//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabResultMap.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabResultMap.Constants.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1	LOINC
        ///2	ScaleType
        ///3	LabChemResultValue.
        /// </summary>
        internal static string ColumnMap {
            get {
                return ResourceManager.GetString("ColumnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment	Non-standard Result
        ///Comment:	Non-standard Result
        ///RESULT/COMMENT:	Non-standard Result
        ///See Comment	Non-standard Result
        ///See scanned report	Non-standard Result
        ///See Below	Non-standard Result
        ///Not Applicable	Non-standard Result
        ///Invalid Result	Non-standard Result
        ///DONE	Non-standard Result
        ///----	Non-standard Result
        ///.....	Non-standard Result
        ///:::::	Non-standard Result
        ///Pending	Non-standard Result
        ///SEE NOTE	Non-standard Result
        ///#	Non-standard Result
        ///##	Non-standard Result
        ///#########	Non-standard Resul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GeneralResults {
            get {
                return ResourceManager.GetString("GeneralResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C	Cel
        ///F	[degF]
        ///mIU/mL	m[IU]/L
        ///nIU/mL	n[IU]/L
        ///IU/ml	IU/mL
        ///IU/ml.	IU/mL
        ///HCV IU/mL	IU/mL
        ////uL	/uL
        ///ul	uL
        ///u/L	U/L
        ///ML	mL
        ///CC	mL
        ///MLS	mL
        ///ml&apos;s	mL
        ///ml.	mL
        ///mls.	mL
        ////ml	/mL
        ///mg	mg
        ///G	g
        ///gm	g
        ///gms	g
        ///grams	g
        ///gm/dl	g/dL
        ///mcg/ml	ug/mL
        ///mg/dl	mg/dL
        ///mg24hrs	mg/(24.h)
        ///mg/24hr	mg/(24.h)
        ///mg/24 hr	mg/(24.h)
        ///mg/24h	mg/(24.h)
        ///mg/24 hr.	mg/(24.h)
        ///mg/24hrs	mg/(24.h)
        ///mg/24 hrs	mg/(24.h)
        ///mg/24.hrs	mg/(24.h)
        ///mg/24.0hrs	mg/(24.h)
        ///mg/224 hr	mg/(24.h)
        ///gm/24 hr.	g/(24.h)
        ///gm/24hr	g/(24.h)
        ///mg/d	mg/d
        ///G/24hr	g/(24. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Helper_Units {
            get {
                return ResourceManager.GetString("Helper_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1a	1a
        ///1b	1b
        ///TYPE 1a	1a
        ///TYPE 1b	1b
        ///2b	2b
        ///3a	3a
        ///Type 1	1
        ///GENOTYPE 1a	1a
        ///Type 2b	2b
        ///GENOTYPE 1b	1b
        ///Type 2	2
        ///TYPE 3a	3a
        ///HCV 1	1
        ///HCV 3	3
        ///1a/1b	1a, 1b
        ///TYPE 3	3
        ///2a/2c	2a, 2c
        ///GENOTYPE 2b	2b
        ///TYPE1B	1b
        ///TYPE1a	1a
        ///TYPE1	1
        ///Genotype 3a	3a
        ///  1a	1a
        ///TYPE 1a/1b	1a, 1b
        ///1 1a	1a
        ///Subtype 1a	1a
        ///1 (NO SUBTYPE)	1
        ///1 UNABLE TO SUBTYPE	1
        ///Subtype1a	1a
        /// 1a	1a
        ///  1b	1b
        ///1a or 1b	1a, 1b
        ///1 NO SUBTYPE	1
        ///TYPE 2a/2c	2a, 2c
        ///2a	2a
        ///Subtype 1b	1b
        ///GENOTYPE 1	1
        ///TYPE 1 Unable to subtype	1
        ///Subtype1b	1b
        ///1, NO SUBTY [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LabMapYale_HepCGenotype {
            get {
                return ResourceManager.GetString("LabMapYale_HepCGenotype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9784-0	LabMapYaleQn_Titer
        ///27215-3	LabMapYaleQn_Titer
        ///7674-5	LabMapYaleQn_Titer
        ///9783-2	LabMapYaleQn_Titer
        ///5048-4	LabMapYaleQn_Titer
        ///5098-9	LabMapYaleQn_Titer
        ///8087-9	LabMapYaleQn_Titer
        ///882-1	LabMapYaleNom_AboRh
        ///883-9	LabMapYaleNom_Abo
        ///21299-3	LabMapYaleNom_Ga
        ///10900-9	LabResultMapYaleOrd_FirstOrLast
        ///13950-1	LabResultMapYaleOrd_FirstOrLast
        ///13951-9	LabResultMapYaleOrd_FirstOrLast
        ///13952-7	LabResultMapYaleOrd_FirstOrLast
        ///13955-0	LabResultMapYaleOrd_FirstOrLast
        ///16128-1	LabResultMapYaleOrd_FirstOrLast [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LabMapYale_Loinc {
            get {
                return ResourceManager.GetString("LabMapYale_Loinc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10333-3	(Color) Appearance in CSF
        ///11138-5	M:E ratio in bone marrow
        ///12258-0	(Urine sediment) Epithelial cell in urine sediment
        ///13351-2	Leukocytes other [#/volume] in CSF)
        ///13528-5	Unidentified cells / 100 leukocytes in body fluid
        ///13655-6	Leukocytes [Presence] in Stool by Light microscopy
        ///13945-1	Erythrocytes in urine sediment
        ///14620-9	(Color) Appearance of pleural fluid
        ///14621-7	(Color) Appearance of peritoneal fluid
        ///14638-1	Calculus analysis
        ///14664-7	(Color) Color of synovial fluid
        ///14860-1	Leukocytes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LabMapYale_LowPriority {
            get {
                return ResourceManager.GetString("LabMapYale_LowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT	X
        ///NOT-	X
        ///NONE	X
        ///NONE-	X
        ///NOR	X
        ///
        ///.
        /// </summary>
        internal static string LabMapYale_NegationWords {
            get {
                return ResourceManager.GetString("LabMapYale_NegationWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General	Normal	Normal
        ///Color	Clear	Clear
        ///Color	Cloudy	Cloudy
        ///Color	Hazy	Hazy
        ///Color	Turbid	Turbid
        ///Color	Colorless	Colorless
        ///Color	Pale Yellow	Pale Yellow
        ///Color	Yellow	Yellow
        ///Color	Dk Yellow	Dark Yellow
        ///Color	Orange	Orange
        ///Color	Amber	Amber
        ///Color	Ltbrn	Light Brown
        ///Color	Red	Red
        ///Color	White	White
        ///Color	Black	Black
        ///PlateletMorph	Large	Large
        ///PlateletMorph	Occ Large	Occasional Large
        ///ANA	Homogeneous	Homogeneous
        ///Culture	No growth after 5 days of incubation.	Neg
        ///Culture	No Growth	Neg
        ///Culture	Less  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LabMapYale_Nom {
            get {
                return ResourceManager.GetString("LabMapYale_Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus	1+	1+
        ///Plus	2+	2+
        ///Plus	3+	3+
        ///Plus	4+	4+
        ///Plus	4+(PACKED FIELD)	4+
        ///Binary	WEAK POSITIVE	Indet
        ///Binary	Weak	Indet
        ///Binary	Equivocal	Indet
        ///Binary	 EQUIVOCAL	Indet
        ///Binary	EQIV	Indet
        ///Binary	EQUIV.	Indet
        ///Binary	Equivical	Indet
        ///Binary	EQUIVO	Indet
        ///Binary	EQUIVOC	Indet
        ///Binary	EQUIVOCA	Indet
        ///Binary	EQUVL	Indet
        ///Binary	 INDETERMINATE	Indet
        ///Binary	BDL	Indet
        ///Binary	BDRLINE	Indet
        ///Binary	BODERLINE	Indet
        ///Binary	BOR	Indet
        ///Binary	BORDERL	Indet
        ///Binary	BORDERLIN	Indet
        ///Binary	BORDERLINE	Indet
        ///Binary	BOR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LabMapYale_Ord {
            get {
                return ResourceManager.GetString("LabMapYale_Ord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qn	LabMapYaleQn
        ///Ord	LabMapYaleOrd
        ///OrdQn	
        ///Nom	LabMapYaleNom
        ///Nar	
        ///Multi	
        ///Doc	
        ///Set	
        ///.
        /// </summary>
        internal static string LabMapYale_Scale {
            get {
                return ResourceManager.GetString("LabMapYale_Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;mustMatchRegex&gt;
        ///  &lt;regex name=&quot;Million&quot;&gt;
        ///    ^(&amp;lt;|&amp;gt;|&amp;lt;=|&amp;gt;=)? ?((0|([1-9](\d{0,11}|\d{0,2}(,\d{3}){0,3})))(\.\d{0,6})?|\.\d{1,6}) (million|mill|mil)$
        ///  &lt;/regex&gt;
        ///  &lt;regex name=&quot;Numeric&quot;&gt;
        ///    ^(&amp;lt;|&amp;gt;|&amp;lt;=|&amp;gt;=)? ?((0|([1-9](\d{0,11}|\d{0,2}(,\d{3}){0,3})))(\.\d{0,6})?|\.\d{1,6})( HCV RNA| DETECTED)?$
        ///  &lt;/regex&gt;
        ///  &lt;regex name=&quot;ExponentialLog&quot;&gt;
        ///    ^(&amp;lt;|&amp;gt;|&amp;lt;=|&amp;gt;=)? ?((0|([1-9](\d{0,11}|\d{0,2}(,\d{3}){0,3})))(\.\d{0,6})?|\.\d{1,6})(E|X10E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LabMapYale_ViralLoad {
            get {
                return ResourceManager.GetString("LabMapYale_ViralLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mill	x
        ///million	x
        ///million iu/ml	x
        ///million copies/ml	x
        ///miilion	x
        ///mil	x
        ///milli0n	x
        ///miliion	x
        ///millio n	x
        ///milion	x
        ///millon	x
        ///miilon	x
        ///milliom	x
        ///millioin	x
        ///miiilion	x
        ///million]	x
        ///million copies.ml	x
        ///.
        /// </summary>
        internal static string LabResultMapYaleQn_Million {
            get {
                return ResourceManager.GetString("LabResultMapYaleQn_Million", resourceCulture);
            }
        }
    }
}
